Repository lblod/app-reglementaire-bijlage, pull requests merged in 2022-09, with the labels that each got.

#8 bump acmidm-login-service
  docker-compose.yml
Labels: bug

#9 Feature/publication
  config/authorization/config.ex
  config/dispatcher/dispatcher.ex
  config/resources/domain.json
  config/resources/editor.json
  docker-compose.yml
Labels: enhancement

#10 Bump frontend version to 1.0.0-beta.3
  docker-compose.yml
Labels: internal

#12 Add migrations to clear bestuurseenheden and set up mock account for abb
  config/migrations/20220919095447-remove-bestuurseenheden.sparql
  config/migrations/20220919111308-set-up-abb-mock-account.sparql
Labels: internal

#15 add raw sparql endpoint (without cache) for use within the frontend
  config/dispatcher/dispatcher.ex
Labels: enhancement

#16 :cloud: Upgrade frontend to 1.0.2
  docker-compose.yml
Labels: internal

#17 :cloud: Upgrade frontend to 1.0.3
  docker-compose.yml
Labels: internal
