Repository lblod/app-reglementaire-bijlage, pull requests merged in 2022-10, with the labels that each got.

#19 chore(deps): bump frontend to v1.1.0
  docker-compose.yml
Labels: internal

#20 chore(deps): bump frontend to v1.1.1
  docker-compose.yml
Labels: internal

#21 :wq
  docker-compose.yml
Labels: internal

#22 Upgrade frontend to 1.1.2
  docker-compose.yml
Labels: internal

#23 Added created on property to skos concept
  config/resources/domain.json
Labels: enhancement

#24 Bump frontend image to version 1.2.0
  data/files/2be6e460-4a29-11ed-93a8-0952da8d7632.html
  data/files/39e13b10-4a29-11ed-93a8-0952da8d7632.html
  docker-compose.yml
Labels: internal

#28 Add position to concept model
  config/resources/domain.json
Labels: enhancement

#27 Feature: json api compliant publisher
  config/authorization/config.ex
  config/dispatcher/dispatcher.ex
  config/migrations/20221018115847-update-published-file-resources.sparql
  config/migrations/20221020090050-move-valid-through-property.sparql
  config/resources/domain.json
  config/resources/editor.json
  data/.DS_Store
  docker-compose.yml
Labels: enhancement

#29 Move publisher port expose from main compose file to dev compose file
  docker-compose.dev.yml
  docker-compose.yml
Labels: bug
