Repository lblod/app-reglementaire-bijlage, pull requests merged in 2023-05, with the labels that each got.

#48 bump frontend to 6.2.0
  docker-compose.yml
Labels: internal

#46 Actually use the cache service
  config/dispatcher/dispatcher.ex
  config/resources/domain.lisp
  docker-compose.yml
Labels: enhancement

#49 Bump frontend to 6.3.0
  docker-compose.yml
Labels: internal

#50 Bump frontend to 6.3.1
  docker-compose.yml
Labels: internal

#51 update mu-cl-resources to 1.22.2
  docker-compose.yml
Labels: bug
