Repository lblod/app-reglementaire-bijlage, pull requests merged in 2023-04, with the labels that each got.

#44 bump frontend to v6.1.0
  docker-compose.yml
Labels: enhancement

#45 Update mu-cl-resources to 1.22.0
  .gitignore
  docker-compose.yml
Labels: internal

#47 move codex route up in the dispatcher
  config/dispatcher/dispatcher.ex
Labels: bug
